<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit9f5280cced7809fe5e8de9a269a440aa
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('ConstantContact\ConstantContactForms\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \ConstantContact\ConstantContactForms\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit9f5280cced7809fe5e8de9a269a440aa', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \ConstantContact\ConstantContactForms\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit9f5280cced7809fe5e8de9a269a440aa', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\ConstantContact\ConstantContactForms\Composer\Autoload\ComposerStaticInit9f5280cced7809fe5e8de9a269a440aa::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
